family_member = input ("give me a family member ")
name = input ("give me a name ")
animal = input ("give me an animal ")
verb = input ("give me a verb ")
place = input ("give me a place ")
place2 = input ("give me the name of an amusement park ")
emotion = input ("give me an emotion ")
adjective = input ("give me an adjective ")
food = input ("give me a food ")
verb2 = input ("give me a verb ")
print ("my " + family_member + "," + name + ", has a " + animal + " that loves to " + verb + " at the " + place + ".")
print ("one day, we went to " + place2 + " and we were very " + emotion + " that it was so " + adjective + ".")
print ("we won a stuffed " + animal + " that looked exactly like the " + animal + " that " + name + " owns.")
print ("we drove back to " + name + " house and we gave the stuffed " + animal + " to the " + animal + " that " + name + " owns.")